apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-app-config
data:
  application.properties: |-
    welcome.message=Kubernetes! Welcome To Spring Boot Hello World App!  
    greeting.message=K8Cluster! Greeting To Spring Boot Hello World App!
    server.port=8082
    spring.jpa.hibernate.ddl-auto=none
    spring.datasource.url=jdbc:mysql://mysql:3306/testdb
    spring.datasource.username=root
    spring.datasource.password=Varijaks1985*0
    logging.level.root=WARN
  
 